### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by autonomousinfantry** [DJArghlex/twitch-notifier-bot#11]
I can not start the bot I'm constantly getting this error:
 Loading dependencies
Loading configuration
Loading functions
Starting Discord interface
 [Error] Disconnected from Discord! Code: 4012, Reason: undefined
***

**Comment by DJArghlex** [comment]
Wrong version of discord.io, use Woor's fork for gateway v6, which i'm suddenly realizing i forgot to include in the instructions

```npm install Woor/discord.io#gateway-v6```

**Comment by gomogoji** [comment]
Thank you!

**Comment by gomogoji** [comment]
I have one more question. Can you explain the twitch app token taking in detail?

**Comment by gomogoji** [comment]
You said ''it's in your URL bar in your bot's app page on the Twitch Developer site'', so client id and app token is same?

**Comment by DJArghlex** [comment]
the thing you need from Twitch is the **Client ID**

so yes, on its page in Twitch's app dashboard, there's a field there with the ID in it

also in the URL of its page

**Comment by Batuhan-maker** [comment]
Pls help me

I don't know how to start the bot, I created start.bat like other discord bots but there was no gene it always gives this error
:
Dependencies are loading
Loading configuration
Loading functions
Launching the Discord interface
[Error] Disconnected from Discord! Code: 4012, Cause: undefined
