### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TheChaoticLion** [DJArghlex/twitch-notifier-bot#4]
package.json save error

**Comment by DJArghlex** [comment]
you kidding me with this, right?

try again

**Comment by TheChaoticLion** [comment]
Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\rkbla>npm install Woor/discord.io#gateway_v6 https config
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\rkbla\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\rkbla\package.json'
npm WARN rkbla No description
npm WARN rkbla No repository field.
npm WARN rkbla No README data
npm WARN rkbla No license field.

+ https@1.0.0
+ config@1.30.0
+ discord.io@2.5.3
updated 3 packages and audited 19 packages in 1.262s
found 0 vulnerabilities


C:\Users\rkbla>
